GET http://localhost:4001

###
GET http://localhost:4001/api

###
GET http://localhost:4001/api/first/10

###
GET http://localhost:4001/api/upload/2021-03-01T22:29:58.888Z

###
POST http://localhost:4001/api/publi
Content-Type: application/json

{
    "title":"recien actualizo la api",
    "body":"a ver que* onda"
}